import { supabase } from './supabase';

export const pdfSeedData = [
   {
     id: "EMP-5337",
     name: "SUSHEEL PAL",
     postAppliedFor: "HELPER",
     jobProcessAssigned: "Finishing & Packing Operations",
     department: "Finishing-1",
     fatherHusbandName: "BRISMOHAN PAL",
     dob: "2003-05-06",
     age: 22,
     contactNo: "8128254258",
     dateOfJoining: "2025-07-04",
     qualification: "10th",
     languages: {
       hindi: { read: true, write: true, speak: true },
       english: { read: false, write: false, speak: false },
       punjabi: { read: false, write: false, speak: true },
       other: { name: "", skill: { read: false, write: false, speak: false } }
     },
     teaBreak1: "15 mins",
     teaBreak2: "15 mins",
     lunchBreak: "30 mins",
     overtimeAllowed: true,
     overtimeHours: "2 hrs/day",
     officeUse: {
       basicPay: 12000,
       esiEmployee: 90,
       pfEmployee: 1440,
       lwfEmployee: 5,
       netCash: 10465,
       esiEmployer: 390,
       pfEmployer: 1440,
       lwfEmployer: 20,
       ctc: 13850,
       applyEsi: true,
       applyPf: true,
       applyLwf: true,
       applyLww: false,
       lwwAllowed: 0,
       lwwAmount: 0,
       bonus: 0
     },
     status: 'active'
   },
   {
     id: "EMP-5338",
     name: "SUMIR KUMAR SINGH",
     postAppliedFor: "HELPER",
     jobProcessAssigned: "Knitting Yarn Loader & Helper",
     department: "Knitting",
     fatherHusbandName: "BALESHWAR SINGH",
     dob: "1994-06-03",
     age: 31,
     contactNo: "7488209407",
     dateOfJoining: "2025-07-04",
     qualification: "10th",
     languages: {
       hindi: { read: true, write: true, speak: true },
       english: { read: true, write: false, speak: true },
       punjabi: { read: false, write: false, speak: false },
       other: { name: "", skill: { read: false, write: false, speak: false } }
     },
     teaBreak1: "15 mins",
     teaBreak2: "15 mins",
     lunchBreak: "30 mins",
     overtimeAllowed: false,
     overtimeHours: "None",
     officeUse: {
       basicPay: 13500,
       esiEmployee: 101,
       pfEmployee: 1620,
       lwfEmployee: 5,
       netCash: 11774,
       esiEmployer: 439,
       pfEmployer: 1620,
       lwfEmployer: 20,
       ctc: 15579,
       applyEsi: true,
       applyPf: true,
       applyLwf: true,
       applyLww: false,
       lwwAllowed: 0,
       lwwAmount: 0,
       bonus: 0
     },
     status: 'active'
   },
   {
     id: "EMP-5339",
     name: "VRIJ BHUSHAN PANDEY",
     postAppliedFor: "FINAL CHECKER",
     jobProcessAssigned: "Final Quality Check & Measurement Audit",
     department: "Finishing-1",
     fatherHusbandName: "GOPAL PANDEY",
     dob: "1983-07-07",
     age: 42,
     contactNo: "62075-92612",
     dateOfJoining: "2025-07-07",
     qualification: "11th",
     languages: {
       hindi: { read: true, write: true, speak: true },
       english: { read: true, write: true, speak: true },
       punjabi: { read: false, write: false, speak: false },
       other: { name: "", skill: { read: false, write: false, speak: false } }
     },
     teaBreak1: "15 mins",
     teaBreak2: "15 mins",
     lunchBreak: "30 mins",
     overtimeAllowed: true,
     overtimeHours: "1.5 hrs/day",
     officeUse: {
       basicPay: 14500,
       esiEmployee: 109,
       pfEmployee: 1740,
       lwfEmployee: 5,
       netCash: 12646,
       esiEmployer: 471,
       pfEmployer: 1740,
       lwfEmployer: 20,
       ctc: 16731,
       applyEsi: true,
       applyPf: true,
       applyLwf: true,
       applyLww: false,
       lwwAllowed: 0,
       lwwAmount: 0,
       bonus: 0
     },
     status: 'active'
   },
   {
     id: "EMP-5340",
     name: "MULENDRA YADAV",
     postAppliedFor: "FINAL CHECKER",
     jobProcessAssigned: "Final Garment Checker & Defect Tagging",
     department: "Finishing-1",
     fatherHusbandName: "KISHUN YADAV",
     dob: "1989-01-11",
     age: 36,
     contactNo: "7033201559",
     dateOfJoining: "2025-07-07",
     qualification: "10th",
     languages: {
       hindi: { read: true, write: true, speak: true },
       english: { read: false, write: false, speak: false },
       punjabi: { read: true, write: false, speak: true },
       other: { name: "", skill: { read: false, write: false, speak: false } }
     },
     teaBreak1: "15 mins",
     teaBreak2: "15 mins",
     lunchBreak: "30 mins",
     overtimeAllowed: true,
     overtimeHours: "2 hrs/day",
     officeUse: {
       basicPay: 13500,
       esiEmployee: 101,
       pfEmployee: 1620,
       lwfEmployee: 5,
       netCash: 11774,
       esiEmployer: 439,
       pfEmployer: 1620,
       lwfEmployer: 20,
       ctc: 15579,
       applyEsi: true,
       applyPf: true,
       applyLwf: true,
       applyLww: false,
       lwwAllowed: 0,
       lwwAmount: 0,
       bonus: 0
     },
     status: 'active'
   },
   {
     id: "EMP-5341",
     name: "VIKAS KUMAR",
     postAppliedFor: "KNITTING",
     jobProcessAssigned: "Circular Knitting Machine Setup & Running",
     department: "Knitting",
     fatherHusbandName: "RAMSI SINGH",
     dob: "1995-05-07",
     age: 30,
     contactNo: "7986036587",
     dateOfJoining: "2025-07-07",
     qualification: "10th",
     languages: {
       hindi: { read: true, write: true, speak: true },
       english: { read: false, write: false, speak: false },
       punjabi: { read: true, write: true, speak: true },
       other: { name: "", skill: { read: false, write: false, speak: false } }
     },
     teaBreak1: "15 mins",
     teaBreak2: "15 mins",
     lunchBreak: "30 mins",
     overtimeAllowed: true,
     overtimeHours: "3 hrs/day",
     officeUse: {
       basicPay: 18000,
       esiEmployee: 135,
       pfEmployee: 1800,
       lwfEmployee: 5,
       netCash: 16060,
       esiEmployer: 585,
       pfEmployer: 1800,
       lwfEmployer: 20,
       ctc: 20405,
       applyEsi: true,
       applyPf: true,
       applyLwf: true,
       applyLww: false,
       lwwAllowed: 0,
       lwwAmount: 0,
       bonus: 0
     },
     status: 'active'
   },
   {
     id: "EMP-5342",
     name: "SONU KUMAR",
     postAppliedFor: "HELPER",
     jobProcessAssigned: "Fabric Cutting Table Sorting & Layering",
     department: "Cutting S/W",
     fatherHusbandName: "RAVINDER SINGH",
     dob: "2003-04-18",
     age: 22,
     contactNo: "8427843171",
     dateOfJoining: "2025-07-09",
     qualification: "12th",
     languages: {
       hindi: { read: true, write: true, speak: true },
       english: { read: true, write: false, speak: false },
       punjabi: { read: false, write: false, speak: false },
       other: { name: "", skill: { read: false, write: false, speak: false } }
     },
     teaBreak1: "15 mins",
     teaBreak2: "15 mins",
     lunchBreak: "30 mins",
     overtimeAllowed: false,
     overtimeHours: "None",
     officeUse: {
       basicPay: 11700,
       esiEmployee: 88,
       pfEmployee: 1404,
       lwfEmployee: 5,
       netCash: 10203,
       esiEmployer: 380,
       pfEmployer: 1404,
       lwfEmployer: 20,
       ctc: 13504,
       applyEsi: true,
       applyPf: true,
       applyLwf: true,
       applyLww: false,
       lwwAllowed: 0,
       lwwAmount: 0,
       bonus: 0
     },
     status: 'active'
   }
];

export const nonEmployeeSeedData = [
  {
    id: "QRY-1001",
    srNo: "QRY-1001",
    category: "Worker",
    name: "RAHUL SHARMA",
    fatherName: "OM PRAKASH SHARMA",
    contactNumber: "9876543210",
    alternateContact: "9812345678",
    reference: "Gate Enquiry / Direct",
    postAppliedFor: "Tailor (Single Needle)",
    dateOfApplication: "2026-08-20",
    qualification: "10th Passed",
    specialSkills: "Overlock, Single Needle Lockstitch",
    computerKnowledge: "None",
    experience: "4 Years at TexGarments Ltd",
    currentSalary: 14000,
    otherPerks: "Room Facility",
    calledForInterview: true,
    interviewDate: "2026-08-22",
    interviewTakenBy: "Production Manager / HR",
    resultOfInterview: "Passed",
    remarks: "Good stitching speed, verified sample collar work",
    offeredToJoin: true,
    salaryDetails: {
      finalSalary: 15500,
      esi: 116,
      esiEmployer: 504,
      pf: 1800,
      pfEmployer: 1800,
      profTax: 0,
      lww: 0,
      lwf: 5,
      lwfEmployer: 20,
      applyEsi: true,
      applyPf: true,
      applyLwf: true,
      ctc: 17824,
      netCashTakeHome: 13579
    },
    status: 'Selected'
  },
  {
    id: "QRY-1002",
    srNo: "QRY-1002",
    category: "Staff",
    name: "ANITA KUMARI",
    fatherName: "RAMESH CHAND",
    contactNumber: "9781203456",
    alternateContact: "9417654321",
    reference: "Vrij Bhushan Pandey (Ref: EMP-5339)",
    postAppliedFor: "Quality Auditor / Data Entry",
    dateOfApplication: "2026-08-21",
    qualification: "Graduate (B.Com)",
    specialSkills: "Garment Inspection & Audit reporting",
    computerKnowledge: "MS Excel, Word, Tally Prime",
    experience: "2.5 Years at Alpha Apparels",
    currentSalary: 16000,
    otherPerks: "Conveyance",
    calledForInterview: true,
    interviewDate: "2026-08-24",
    interviewTakenBy: "Quality Head & HR Lead",
    resultOfInterview: "Selected",
    remarks: "Proficient in Excel and measurement chart verification",
    offeredToJoin: true,
    salaryDetails: {
      finalSalary: 18000,
      esi: 135,
      esiEmployer: 585,
      pf: 1800,
      pfEmployer: 1800,
      profTax: 0,
      lww: 0,
      lwf: 5,
      lwfEmployer: 20,
      applyEsi: true,
      applyPf: true,
      applyLwf: true,
      ctc: 20405,
      netCashTakeHome: 16060
    },
    status: 'Selected'
  },
  {
    id: "QRY-1003",
    srNo: "QRY-1003",
    category: "Worker",
    name: "MANOJ KUMAR PASWAN",
    fatherName: "SURENDRA PASWAN",
    contactNumber: "8899001122",
    alternateContact: "",
    reference: "Security Desk Entry",
    postAppliedFor: "Helper (Cutting Table)",
    dateOfApplication: "2026-08-25",
    qualification: "8th Standard",
    specialSkills: "Fabric Layering, Bundling",
    computerKnowledge: "None",
    experience: "Fresher",
    currentSalary: 0,
    otherPerks: "None",
    calledForInterview: false,
    interviewDate: "",
    interviewTakenBy: "",
    resultOfInterview: "Under Consideration",
    remarks: "Application received at gate, pending line helper slot",
    offeredToJoin: false,
    salaryDetails: {
      finalSalary: 0,
      esi: 0,
      esiEmployer: 0,
      pf: 0,
      pfEmployer: 0,
      profTax: 0,
      lww: 0,
      lwf: 5,
      lwfEmployer: 20,
      applyEsi: true,
      applyPf: true,
      applyLwf: true,
      ctc: 0,
      netCashTakeHome: 0
    },
    status: 'Query'
  }
];

export async function seedDatabase() {
  const now = new Date().toISOString();

  const employeeRows = pdfSeedData.map(({ id, ...rest }) => ({
    id,
    data: { ...rest, createdAt: now, updatedAt: now },
  }));
  const { error: empError } = await supabase.from('employees').upsert(employeeRows);
  if (empError) throw empError;

  const nonEmployeeRows = nonEmployeeSeedData.map(({ id, ...rest }) => ({
    id,
    data: { ...rest, createdAt: now, updatedAt: now },
  }));
  const { error: nonEmpError } = await supabase.from('non_employees').upsert(nonEmployeeRows);
  if (nonEmpError) throw nonEmpError;
}
